### PR TITLE
Frontend Overhaul + New talks

### PR DESCRIPTION
**Pull request by christiansherry**

### CODE REVIEW

**Comment by christiansherry** [comment]
* Overhaul of site theme
* Added Stu Herberts talk and My talk with slides and videos

I've added some copy, mainly into the straplines at the top of each page. These will need reviewing before this is put live or soon after.

**Comment by christiansherry** [comment]
Also needs details of the next event.

**Comment by dave1010** [comment]
@christiansherry looks good. Can you remove / fix the failing tests? Do you have a screenshot so @fullybaked / @HughbertD can see it before it goes live?

**Comment by christiansherry** [comment]
@dave1010 @HughbertD @rossey @fullybaked 

http://postimg.org/image/luoegwgh1/
http://postimg.org/image/8p8wasmlh/
http://postimg.org/image/rf0vrjfc5/
http://postimg.org/image/lj6y45011/

**Comment by fullybaked** [comment]
:+1:  awesome work Chris :smiley:

**Comment by HughbertD** [comment]
This is wicked. Thanks Chris! +1

**Pull request merged**
