### PR TITLE
Change title to say TONIGHT for talk on current date

### PR DESCRIPTION
**Pull request by chrisnx**
Date logic is a mess, ill look at cleaning this up soon with
yaml / mongo instead of the json file we have now. This is a
quick fix.

### CODE REVIEW

**Comment by rossey** [comment]
Yeah it's also got the events the wrong way around so there's a sort issue too :). Mongo might be overkill for this, but +1 YAML

**Comment by dave1010** [comment]
https://www.eventbrite.co.uk/support/articles/en_US/How_To/how-to-sell-eventbrite-tickets-registrations-on-your-website-using-embeddable-widgets?lg=en_GB

**Comment by chrisnx** [comment]
@dave1010 that got started but was never finished. https://github.com/PHPDorset/phpdorset.github.io/issues/13

**Comment by rossey** [comment]
@dave1010 we already have eventbrite buttons :)

**Pull request merged**
